### ISSUE TITLE
2 letter username (space in between) not working well

### ISSUE THREAD

**Issue by kamaleshlunkad** [diogo-fernan/ir-rescue#13]
ir-rescue-win-v1.4.3 20190326  9:08:26.41 (India Standard Time): "tools-win\activ\exiftool.exe -csv C:\Users\*Forensic*\AppData\Roaming\Microsoft\Windows\Recent\*" 
 
No matching files
 
ir-rescue-win-v1.4.3 20190326  9:08:27.82 (India Standard Time): "tools-win\activ\exiftool.exe -csv C:\Users\*Forensic*\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\*" 
 
No matching files
 

Actual User name is "Forensic Workstation"

**Comment by diogo-fernan** [comment]
Could you share the file `ir-rescue-win.log`?
