### ISSUE TITLE
AV detecting two files

### ISSUE THREAD

**Issue by Derekt2** [diogo-fernan/ir-rescue#17]
While this isn't an issue with the project, the default use on windows is blocked by defender. Two files are the culprit, should we consider updating or replacing? 
\win\tools-win\fs\ExtractUsnJrnl.exe
\win\tools-win\fs\RawCopy64.exe
this project is great by the way!

**Comment by diogo-fernan** [comment]
Hi there! Unfortunately there is nothing that can be done about that other than submitting the files as false-positive detections to Microsoft via their submission portal as per https://docs.microsoft.com/en-us/windows/security/threat-protection/intelligence/submission-guide, which might require a business account.

The tools could definitely use an update to newer versions (where applicable), just have not had time for that in recent times!
