### ISSUE TITLE
Compressed folder on windows after using the .bat

### ISSUE THREAD

**Issue by Raffael93** [diogo-fernan/ir-rescue#23]
I used the file ir-rescue-win.bat to analyse the PC. And at the end, i got a compressed archive.
I want to open it but i can't because i need a password, i tried the password of the VM but didn't work.
What is the password ?

![mdp](https://user-images.githubusercontent.com/39736925/165965486-7d6bf76f-3cab-47d1-98ff-d78b7db8f670.PNG)
.

**Comment by diogo-fernan** [comment]
Hello @Raffael93. The default password is `infected`. You can change it in the configuration file here: https://github.com/diogo-fernan/ir-rescue/blob/master/win/tools-win/cfg/ir-rescue-win.conf#L34.
