### ISSUE TITLE
Automatically update the tools

### ISSUE THREAD

**Issue by fmurer** [diogo-fernan/ir-rescue#9]
Hi,
First, I like your tool. Would there be a way to automatically update all the used tools? Like a second script that checks if the tools are up to date and in case not download the newest version.

**Comment by diogo-fernan** [comment]
Hello Fabian,

New versions of tools are often not backward compatible, changing program switches or features. WinPmem is an example of that, incorporating AFF4 compatibility that replaced raw memory dumping.

Your idea is good and could perhaps be implemented with the above-mentioned caveat. Would you like to contribute to that? :-)

Cheers,
Diogo
